.include "macro.inc"

#
#   Automatically generated by mkdmadata.py at build time
#

.macro DMA_TABLE_ENTRY segment
    .4byte _\segment\()SegmentRomStart
    .4byte _\segment\()SegmentRomEnd
    .4byte _\segment\()SegmentRomStart
    .4byte 0
.endm

glabel gDmaDataTable
# Generated from spec by build
.include "include/dmadata.inc"

# Why the empty space?
.space 0x100
