extern Vtx gGiCompassGlassDL_gGiCompassGlassDL_mesh_layer_Transparent_vtx_cull[8];
extern Vtx gGiCompassGlassDL_gGiCompassGlassDL_mesh_layer_Transparent_vtx_0[10];
extern Gfx gGiCompassGlassDL_gGiCompassGlassDL_mesh_layer_Transparent_tri_0[];
extern Gfx mat_gGiCompassGlassDL_f3d_material_006_layerTransparent[];
extern Gfx gGiCompassGlassDL[];
