extern Vtx gSWLinkAdultMegatonHammerInHandDL_gSWLinkAdultMegatonHammerInHandDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gSWLinkAdultMegatonHammerInHandDL_gSWLinkAdultMegatonHammerInHandDL_mesh_layer_Opaque_vtx_0[9];
extern Gfx gSWLinkAdultMegatonHammerInHandDL_gSWLinkAdultMegatonHammerInHandDL_mesh_layer_Opaque_tri_0[];
extern Vtx gSWLinkAdultMegatonHammerInHandDL_gSWLinkAdultMegatonHammerInHandDL_mesh_layer_Opaque_vtx_1[182];
extern Gfx gSWLinkAdultMegatonHammerInHandDL_gSWLinkAdultMegatonHammerInHandDL_mesh_layer_Opaque_tri_1[];
extern Gfx mat_gSWLinkAdultMegatonHammerInHandDL_f3d_material_092_layerOpaque[];
extern Gfx mat_gSWLinkAdultMegatonHammerInHandDL_MasterSwordMetal_layerOpaque[];
extern Gfx gSWLinkAdultMegatonHammerInHandDL[];
