extern u64 gSWLinkAdultOOTInHandDL_ocarina_32x16_rgba16[];
extern Vtx gSWLinkAdultOOTInHandDL_gSWLinkAdultOOTInHandDL_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gSWLinkAdultOOTInHandDL_gSWLinkAdultOOTInHandDL_mesh_layer_Opaque_vtx_0[26];
extern Gfx gSWLinkAdultOOTInHandDL_gSWLinkAdultOOTInHandDL_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gSWLinkAdultOOTInHandDL_f3d_material_045_layerOpaque[];
extern Gfx gSWLinkAdultOOTInHandDL[];
