extern u64 gBridgePiece_deku_tree_room_00Tex_00C360_rgb5a1_ci8[];
extern u64 gBridgePiece_deku_tree_room_00Tex_00C360_rgb5a1_ci8_pal_rgba16[];
extern Vtx gBridgePiece_bridgepiece_mesh_layer_Opaque_vtx_cull[8];
extern Vtx gBridgePiece_bridgepiece_mesh_layer_Opaque_vtx_0[71];
extern Gfx gBridgePiece_bridgepiece_mesh_layer_Opaque_tri_0[];
extern Gfx mat_gBridgePiece_BridgePlank_layerOpaque[];
extern Gfx gBridgePiece[];
